const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const {spawnSync} = require('node:child_process');
const gate = path.resolve(__dirname,'verify-hotfix-patch-catalog.cjs');

test('explicit private context retains the full gate and fails closed on bad declarations', t => {
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cg-catalog-context-'));
 t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 fs.mkdirSync(path.join(dir,'cmd','clusterguard'),{recursive:true});
 fs.writeFileSync(path.join(dir,'go.mod'),'module clusterguard.io/ha\n\ngo 1.22\n');
 fs.writeFileSync(path.join(dir,'cmd','clusterguard','main.go'),'package main\nfunc main() {}\n');
 const specs=path.join(dir,'specs');fs.mkdirSync(specs);
 const ledger=path.join(dir,'ledger.json');
 const en=path.join(dir,'en.md'),zh=path.join(dir,'zh.md');
 fs.writeFileSync(en,'Generated by `scripts/render-hotfix-catalog.cjs`');
 fs.writeFileSync(zh,'由 `scripts/render-hotfix-catalog.cjs`');
 const args=['--repo',dir,'--spec-dir',specs,'--ledger',ledger,'--catalog-en',en,'--catalog-zh',zh];
 const run=(extra=[])=>spawnSync(process.execPath,[gate,...args,...extra],{encoding:'utf8'});
 let r=run();assert.equal(r.status,1);assert.match(r.stderr,/FAIL the publication ledger parses.*not found/);
 fs.writeFileSync(ledger,JSON.stringify({schema_version:1,publications:[]}));
 r=run();assert.equal(r.status,1);assert.match(r.stdout,/ok   the publication ledger parses/);assert.match(r.stderr,/FAIL hotfix declarations exist/);assert.match(r.stdout,/ok   the hotfix catalogue exists in both languages/);
 fs.writeFileSync(path.join(specs,'broken.json'),'{');r=run();assert.equal(r.status,1);assert.match(r.stderr,/FAIL every JSON document.*broken.json/);
 fs.writeFileSync(path.join(specs,'broken.json'),'null');r=run();assert.equal(r.status,1);assert.match(r.stderr,/FAIL every JSON document.*broken.json/);assert.doesNotMatch(r.stderr,/TypeError/);
 fs.rmSync(path.join(specs,'broken.json'));
 const validEntry={file:'release/line/patch.cgpatch',sha256:'a'.repeat(64),size:1,status:'frozen'};
 for(const malformed of [{schema_version:1,publications:[validEntry,validEntry]},{schema_version:99,publications:[]},{schema_version:1,publications:{}},{schema_version:1,publications:[{file:'release/../../outside'}]}]) {
  fs.writeFileSync(ledger,JSON.stringify(malformed));r=run();assert.equal(r.status,1);assert.match(r.stderr,/FAIL the publication ledger parses/);assert.doesNotMatch(r.stderr,/TypeError|SyntaxError/);
 }
 r=run(['--ledgre',ledger]);assert.equal(r.status,2);assert.match(r.stderr,/unknown argument/);
 r=run(['--ledger']);assert.equal(r.status,2);assert.match(r.stderr,/missing value/);
});
